### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [bahamas10/node-exec#11]
I get this error after about 15 minutes of running another nodejs script. I'm using it for other stuff and it works just fine.  The script I'm running dumps a huge amount to the shell for output - I wonder if that could be causing the issue.

```
/tmp/shelljs_70dbcc9e7102d53da62f:4
  fs.writeFileSync('/tmp/shelljs_5942f59f9138177745a1', err ? err.code.toString() : '0');

TypeError: Cannot read property 'toString' of undefined
    at /tmp/shelljs_70dbcc9e7102d53da62f:4:71
    at ChildProcess.exithandler (child_process.js:210:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
shell.js: internal error
Error: Command failed: "/usr/bin/node" /tmp/shelljs_70dbcc9e7102d53da62f
    at checkExecSyncError (child_process.js:441:13)
    at Object.execSync (child_process.js:481:13)
    at execSync (/data_collection/node_modules/shelljs/src/exec.js:81:11)
    at _exec (/data_collection/node_modules/shelljs/src/exec.js:214:12)
    at /data_collection/node_modules/shelljs/src/common.js:182:23
    at run (/data_collection/MY_NODE_FILE.js:16:18)
    at Object.<anonymous> (/data_collection/tx_runAllMonthlyDataCollection.js:31:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

**Comment by bahamas10** [comment]
I don't see node_modules/exec in this stack trace at all... are you sure it is this module?
